"""Shell completion (SPEC-0022): script emit/install + dynamic completers.

Install tests use a tmp --dest / tmp HOME+XDG — never the real fish/bash/zsh dirs.
"""
from pathlib import Path
from zoneinfo import ZoneInfo

import pytest
import yaml
from click.core import Context
from click.testing import CliRunner

from wt import completion as C
from wt import org_write as W
from wt.cli import cli
from wt.specs import scaffold_outbound

ROOT = Path(__file__).resolve().parent.parent


def _cfg(tmp_path, *, mappings=None, outbox_targets=None):
    org = tmp_path / "org"
    org.mkdir()
    data = tmp_path / "data"
    data.mkdir()
    specs_dir = tmp_path / "specs"
    specs_dir.mkdir()
    for name in ("TEMPLATE.md", "TEMPLATE-epic.md"):
        (specs_dir / name).write_text((ROOT / "docs" / "specs" / name).read_text())
    # Copy a couple of real-looking numbered specs for SPEC-id completion
    for src in sorted((ROOT / "docs" / "specs").glob("0003-*.md"))[:1]:
        (specs_dir / src.name).write_text(src.read_text())
    for src in sorted((ROOT / "docs" / "specs").glob("0004-*.md"))[:1]:
        (specs_dir / src.name).write_text(src.read_text())
    config_dir = tmp_path / "config"
    config_dir.mkdir()
    if mappings:
        (config_dir / "mappings.yaml").write_text(yaml.safe_dump(mappings))
    outbox = tmp_path / "outbox"
    outbox.mkdir()
    return {
        "org_files": [str(org)],
        "org_todo_keywords": ["TODO", "INPROGRESS", "|", "DONE"],
        "org_idea_keywords": ["IDEA", "INCUBATE", "SPECCED", "|", "PROMOTED", "DROPPED"],
        "timezone": "America/New_York",
        "_tz": ZoneInfo("America/New_York"),
        "data_dir": str(data),
        "org_capture_file": str(org / "inbox.org"),
        "org_ideas_file": str(org / "ideas.org"),
        "specs_dir": str(specs_dir),
        "outbox_dir": str(outbox),
        "config_dir": str(config_dir),
        "project_axis": "bucket",
        "outbox_targets": outbox_targets or {"thjalfi": {"repo_path": "/tmp/thjalfi"}},
    }


def _ctx(cfg):
    ctx = Context(cli)
    ctx.obj = cfg
    return ctx


# ---- source / CLI print ---------------------------------------------------------------

@pytest.mark.parametrize("shell", list(C.SHELLS))
def test_source_script_contains_complete_var_and_prog(shell):
    src = C.source_script(shell)
    assert src.startswith(C._MARKER.rstrip("\n"))
    assert "_WT_COMPLETE" in src
    assert "wt" in src
    assert src.strip()


@pytest.mark.parametrize("shell", list(C.SHELLS))
def test_cli_completion_print(shell):
    r = CliRunner().invoke(cli, ["completion", shell])
    assert r.exit_code == 0, r.output
    assert "_WT_COMPLETE" in r.output
    assert "wt" in r.output


def test_source_script_rejects_unknown_shell():
    with pytest.raises(ValueError, match="unsupported"):
        C.source_script("tcsh")


# ---- install --------------------------------------------------------------------------

def test_install_writes_dest_and_is_idempotent(tmp_path):
    dest = tmp_path / "completions" / "wt.fish"
    path = C.install("fish", dest=dest)
    assert path == dest
    assert dest.is_file()
    assert "_WT_COMPLETE" in dest.read_text()
    # second install: same content → no error
    path2 = C.install("fish", dest=dest)
    assert path2 == dest


def test_install_refuses_divergent_unmanaged_without_force(tmp_path):
    dest = tmp_path / "wt.fish"
    dest.write_text("# hand-written\ncomplete -c wt\n")
    with pytest.raises(ValueError, match="not a wt-generated"):
        C.install("fish", dest=dest)
    C.install("fish", dest=dest, force=True)
    assert dest.read_text().startswith("# generated by wt completion")


def test_install_default_path_respects_xdg(tmp_path, monkeypatch):
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "cfg"))
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    fish = C.default_install_path("fish")
    assert fish == tmp_path / "cfg" / "fish" / "completions" / "wt.fish"
    bash = C.default_install_path("bash")
    assert bash == tmp_path / "data" / "bash-completion" / "completions" / "wt"
    zsh = C.default_install_path("zsh")
    assert zsh == tmp_path / "data" / "zsh" / "site-functions" / "_wt"
    path = C.install("fish")
    assert path == fish
    assert fish.is_file()


def test_cli_completion_install(tmp_path):
    dest = tmp_path / "wt.bash"
    r = CliRunner().invoke(cli, ["completion", "install", "--shell", "bash",
                                 "--dest", str(dest)])
    assert r.exit_code == 0, r.output
    assert dest.is_file()
    assert "bash completion" in r.output or str(dest) in r.output


# ---- dynamic completers ---------------------------------------------------------------

def test_complete_project(tmp_path):
    cfg = _cfg(tmp_path, mappings={"thjalfi": {"bucket": "Thjalfi"},
                                   "other": {"bucket": "Logging"}})
    items = C.complete_project(_ctx(cfg), None, "Th")
    values = [i.value for i in items]
    assert values == ["Thjalfi"]


def test_complete_idea_id(tmp_path):
    cfg = _cfg(tmp_path)
    W.add_idea(cfg, "shell completion idea")
    items = C.complete_idea_id(_ctx(cfg), None, "IDEA-")
    values = [i.value for i in items]
    assert any(v.startswith("IDEA-") for v in values)
    by_id = {i.value: i for i in items}
    assert by_id["IDEA-001"].help and "shell completion idea" in by_id["IDEA-001"].help


def test_clip_help_caps_length():
    long = "word " * 40
    h = C._clip_help(long, maxlen=40)
    assert len(h) <= 40
    assert h.endswith("…")


def test_complete_spec_id(tmp_path):
    cfg = _cfg(tmp_path)
    items = C.complete_spec_id(_ctx(cfg), None, "SPEC-000")
    values = [i.value for i in items]
    assert "SPEC-0003" in values
    assert "SPEC-0004" in values


def test_complete_outbound_id(tmp_path):
    cfg = _cfg(tmp_path)
    scaffold_outbound(cfg, "thjalfi", title="Outbound completion test")
    items = C.complete_outbound_id(_ctx(cfg), None, "THJALFI-")
    values = [i.value for i in items]
    assert any(v.startswith("THJALFI-") for v in values)


def test_complete_scheme_and_emit():
    schemes = [i.value for i in C.complete_scheme(_ctx({}), None, "")]
    assert "wt-native" in schemes
    emits = [i.value for i in C.complete_emit(_ctx({}), None, "")]
    assert "spec" in emits or "contract" in emits or emits  # at least some artifacts


def test_complete_todo_and_idea_state(tmp_path):
    cfg = _cfg(tmp_path)
    todos = [i.value for i in C.complete_todo_state(_ctx(cfg), None, "")]
    assert "TODO" in todos and "DONE" in todos and "INPROGRESS" in todos
    ideas = [i.value for i in C.complete_idea_state(_ctx(cfg), None, "IN")]
    assert "INCUBATE" in ideas


def test_complete_outbox_target(tmp_path):
    cfg = _cfg(tmp_path)
    values = [i.value for i in C.complete_outbox_target(_ctx(cfg), None, "th")]
    assert values == ["thjalfi"]


def test_path_option_has_path_type():
    """Path options use click.Path so Click's built-in file/dir completion applies."""
    export = cli.commands["export"]
    out_opt = next(p for p in export.params if "--out" in p.opts or "-o" in p.opts)
    assert out_opt.type.name == "path"


def test_completers_soft_fail_on_broken_cfg():
    bad = {"config_dir": "/nonexistent/wt-config-xyz", "org_files": ["/nope"],
           "data_dir": "/nope", "specs_dir": "/nope", "outbox_dir": "/nope",
           "org_todo_keywords": ["TODO", "|", "DONE"],
           "org_idea_keywords": ["IDEA", "|", "PROMOTED"]}
    ctx = _ctx(bad)
    assert C.complete_project(ctx, None, "") == []
    assert C.complete_idea_id(ctx, None, "") == []
    assert C.complete_spec_id(ctx, None, "") == []
    assert C.complete_outbound_id(ctx, None, "") == []
    assert C.complete_mapped_topic(ctx, None, "") == []
    assert C.complete_task_selector(ctx, None, "") == []


def test_complete_mapped_topic(tmp_path):
    cfg = _cfg(tmp_path, mappings={"thjalfi": "Thjalfi", "drone": {"bucket": "X", "area": "y"}})
    values = [i.value for i in C.complete_mapped_topic(_ctx(cfg), None, "th")]
    assert values == ["thjalfi"]


# ---- SPEC-0039: idea selectors + compliance ------------------------------------------

def test_idea_show_selector_wired_and_completes(tmp_path):
    from wt.cli import idea_show_cmd
    sel = next(p for p in idea_show_cmd.params if p.name == "selector")
    assert sel.shell_complete is not None

    cfg = _cfg(tmp_path)
    W.add_idea(cfg, "completion for show")
    values = [i.value for i in C.complete_idea_id(_ctx(cfg), None, "IDEA-")]
    assert "IDEA-001" in values


def test_required_shell_complete_names_wired():
    """Every CLI param whose name is in REQUIRED_SHELL_COMPLETE_NAMES must have a completer."""
    missing = C.missing_required_shell_completes()
    assert missing == [], (
        "attach shell_complete=C.complete_… (or Path/Choice) for:\n  - "
        + "\n  - ".join(missing)
        + "\nOr remove the name from REQUIRED_SHELL_COMPLETE_NAMES if free-text is intentional."
    )


def test_required_shell_complete_registry_nonempty():
    assert "selector" in C.REQUIRED_SHELL_COMPLETE_NAMES
    assert "outbound_id" in C.REQUIRED_SHELL_COMPLETE_NAMES
