"""Shell completion for wt (SPEC-0022): Click 8 script emit/install + dynamic
`shell_complete` callbacks for high-value CLI values (projects, topics, states, SPEC/idea
selectors, schemes, paths, …).

Completers **fail soft** — any load/parse error yields `[]` so a broken config never
crashes the shell prompt. Script generation uses Click's built-in
`_WT_COMPLETE=<shell>_{source,complete}` protocol; no third-party deps.
"""
from __future__ import annotations

import os
from pathlib import Path

import click
from click.shell_completion import CompletionItem, get_completion_class

from .config import load_config
from .org import _split_keywords, filter_tasks, load_tasks
from .rules import known_projects, load_mappings
from .specmeta import split_frontmatter
from .specs import _outbound_specs, _specs_dir, known_epics
from .export_schemes import available as available_schemes

SHELLS = ("bash", "zsh", "fish")
COMPLETE_VAR = "_WT_COMPLETE"
PROG_NAME = "wt"

# Marker comment so install can recognize a file we wrote (and distinguish unmanaged).
_MARKER = "# generated by wt completion (SPEC-0022)\n"

# Parameter *names* that must carry a custom shell_complete (or Path/Choice) — SPEC-0039.
# Free-text args (text, title, note, dates, …) are intentionally omitted.
REQUIRED_SHELL_COMPLETE_NAMES = frozenset({
    "selector",      # idea id or task selector — wire the right completer per command
    "from_idea",
    "outbound_id",
    "spec_id",
    "scheme",
    "emit",
    "project",
    "epic",
    "state",
    "by",
    "raw",
    "new_state",
    "workstream",    # SPEC-0090 curated lanes from config
    "key",           # SPEC-0122 idea ext keys when schema exists
})


def source_script(shell: str) -> str:
    """Emit Click's completion source for `wt` / `_WT_COMPLETE` for bash|zsh|fish."""
    if shell not in SHELLS:
        raise ValueError(f"unsupported shell: {shell!r} (expected one of {SHELLS})")
    # Lazy import: cli.py imports this module for the completion group + callbacks.
    from .cli import cli
    cls = get_completion_class(shell)
    if cls is None:
        raise ValueError(f"Click has no completion class for shell {shell!r}")
    body = cls(cli, {}, PROG_NAME, COMPLETE_VAR).source()
    if not body.endswith("\n"):
        body += "\n"
    return _MARKER + body


def default_install_path(shell: str) -> Path:
    """Conventional user install path for the given shell (XDG-aware where applicable)."""
    if shell not in SHELLS:
        raise ValueError(f"unsupported shell: {shell!r}")
    home = Path.home()
    xdg_data = Path(os.environ.get("XDG_DATA_HOME") or (home / ".local" / "share"))
    xdg_config = Path(os.environ.get("XDG_CONFIG_HOME") or (home / ".config"))
    if shell == "fish":
        return xdg_config / "fish" / "completions" / "wt.fish"
    if shell == "bash":
        return xdg_data / "bash-completion" / "completions" / "wt"
    # zsh
    return xdg_data / "zsh" / "site-functions" / "_wt"


def install(shell: str, *, dest=None, force: bool = False) -> Path:
    """Write the completion script to `dest` (or the shell's default path). Creates parent
    dirs. Idempotent when content already matches. Refuses to overwrite a divergent
    unmanaged file unless `force`. Returns the path written (or already present)."""
    if shell not in SHELLS:
        raise ValueError(f"unsupported shell: {shell!r}")
    path = Path(dest) if dest else default_install_path(shell)
    script = source_script(shell)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == script:
            return path
        ours = existing.startswith(_MARKER.rstrip("\n")) or _MARKER in existing[:80]
        if not ours and not force:
            raise ValueError(
                f"{path} already exists and is not a wt-generated completion file "
                f"(pass --force to overwrite)")
        if ours and not force and existing != script:
            # Our file but content drifted (e.g. CLI grew) — refresh without requiring
            # --force when the marker is present.
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(script, encoding="utf-8")
    return path


# ---- completer helpers ----------------------------------------------------------------

def _cfg_from_ctx(ctx) -> dict:
    """Prefer ctx.obj (Config dict) when present; otherwise load_config(). Soft-fail
    callers wrap this."""
    c = ctx
    while c is not None:
        if isinstance(getattr(c, "obj", None), dict) and "config_dir" in c.obj:
            return c.obj
        c = c.parent
    return load_config()


def _prefix_filter(values, incomplete: str):
    inc = incomplete or ""
    return [v for v in values if str(v).startswith(inc)]


def _clip_help(text, maxlen: int = 72) -> str:
    """Single-line help for CompletionItem; word-boundary trim (SPEC-0040)."""
    s = " ".join(str(text or "").split())
    if len(s) <= maxlen:
        return s
    cut = s[: maxlen - 1].rsplit(" ", 1)[0] or s[: maxlen - 1]
    return cut + "…"


def _items(values, incomplete: str, *, helps=None) -> list[CompletionItem]:
    helps = helps or {}
    out = []
    for v in _prefix_filter(values, incomplete):
        key = str(v)
        h = helps.get(key)
        out.append(CompletionItem(key, help=_clip_help(h) if h else None))
    return out


def _soft(fn):
    """Wrap a completer so any exception becomes []."""
    def wrapper(ctx, param, incomplete):
        try:
            return fn(ctx, param, incomplete)
        except Exception:
            return []
    wrapper.__name__ = getattr(fn, "__name__", "completer")
    wrapper.__doc__ = getattr(fn, "__doc__", None)
    return wrapper


@_soft
def complete_project(ctx, param, incomplete):
    return _items(known_projects(_cfg_from_ctx(ctx)), incomplete)


@_soft
def complete_workstream(ctx, param, incomplete):
    from .org_write import configured_workstreams
    return _items(configured_workstreams(_cfg_from_ctx(ctx)), incomplete)


@_soft
def complete_ext_key(ctx, param, incomplete):
    """Ext property keys from schema (SPEC-0122). Needs --project or selector with :PROJECT:."""
    cfg = _cfg_from_ctx(ctx)
    from .extension_schema import extension_keys_for
    project = ctx.params.get("project")
    if not project and ctx.params.get("selector"):
        try:
            from .org_write import resolve_selector
            task = resolve_selector(cfg, ctx.params["selector"])
            project = task.properties.get("PROJECT")
        except Exception:
            pass
    if not project:
        return []
    return _items(extension_keys_for(cfg, project), incomplete)


@_soft
def complete_epic(ctx, param, incomplete):
    return _items(known_epics(_cfg_from_ctx(ctx)), incomplete)


@_soft
def complete_todo_state(ctx, param, incomplete):
    cfg = _cfg_from_ctx(ctx)
    active, done = _split_keywords(cfg.get("org_todo_keywords") or ["TODO", "|", "DONE"])
    return _items(active + done, incomplete)


@_soft
def complete_idea_state(ctx, param, incomplete):
    cfg = _cfg_from_ctx(ctx)
    active, done = _split_keywords(
        cfg.get("org_idea_keywords") or [
            "IDEA", "INCUBATE", "SPECCED", "|", "PROMOTED", "EXPORTED", "SHIPPED", "DROPPED"])
    return _items(active + done, incomplete)


@_soft
def complete_by_axis(ctx, param, incomplete):
    cfg = _cfg_from_ctx(ctx)
    axes = {"project", "topic", cfg.get("project_axis", "bucket")}
    try:
        for facets in load_mappings(cfg).values():
            axes.update(facets.keys())
    except Exception:
        pass
    return _items(sorted(axes), incomplete)


@_soft
def complete_idea_id(ctx, param, incomplete):
    cfg = _cfg_from_ctx(ctx)
    tasks = filter_tasks(load_tasks(cfg), is_idea=True, done=False)
    ids, helps = [], {}
    for t in tasks:
        if not t.id:
            continue
        ids.append(t.id)
        if t.heading:
            helps[t.id] = t.heading
    return _items(ids, incomplete, helps=helps)


@_soft
def complete_spec_id(ctx, param, incomplete):
    cfg = _cfg_from_ctx(ctx)
    specs_dir = _specs_dir(cfg)
    ids = []
    if specs_dir.exists():
        for path in specs_dir.glob("[0-9]*.md"):
            fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
            fm = fm or {}
            if fm.get("id"):
                ids.append(fm["id"])
    return _items(sorted(ids), incomplete)


@_soft
def complete_outbound_id(ctx, param, incomplete):
    cfg = _cfg_from_ctx(ctx)
    ids = [s["fm"]["id"] for s in _outbound_specs(cfg) if s.get("fm", {}).get("id")]
    return _items(sorted(ids), incomplete)


@_soft
def complete_any_spec_id(ctx, param, incomplete):
    """Internal + outbound spec ids together (SPEC-0069, e.g. `wt spec postmortem`)."""
    cfg = _cfg_from_ctx(ctx)
    ids = []
    specs_dir = _specs_dir(cfg)
    if specs_dir.exists():
        for path in specs_dir.glob("[0-9]*.md"):
            fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
            fm = fm or {}
            if fm.get("id"):
                ids.append(fm["id"])
    ids.extend(s["fm"]["id"] for s in _outbound_specs(cfg) if s.get("fm", {}).get("id"))
    return _items(sorted(ids), incomplete)


@_soft
def complete_scheme(ctx, param, incomplete):
    return _items([s.name for s in available_schemes()], incomplete)


@_soft
def complete_emit(ctx, param, incomplete):
    arts = []
    for s in available_schemes():
        arts.extend(s.artifacts)
    return _items(sorted(set(arts)), incomplete)


@_soft
def complete_outbox_target(ctx, param, incomplete):
    cfg = _cfg_from_ctx(ctx)
    keys = sorted((cfg.get("outbox_targets") or {}).keys())
    return _items(keys, incomplete)


@_soft
def complete_task_selector(ctx, param, incomplete):
    cfg = _cfg_from_ctx(ctx)
    tasks = filter_tasks(load_tasks(cfg), is_idea=False, done=False)
    cand = []
    for t in tasks:
        if t.topic_key:
            cand.append(t.topic_key)
        if t.id and not str(t.id).endswith(f":{t.line}"):  # prefer stable :ID: over file:line
            cand.append(t.id)
        elif t.id:
            cand.append(t.id)
    # de-dupe preserving order
    seen, out = set(), []
    for c in cand:
        if c not in seen:
            seen.add(c)
            out.append(c)
    return _items(out, incomplete)


@_soft
def complete_mapped_topic(ctx, param, incomplete):
    """Base topics already present in mappings.yaml (cheap; no transcript re-ingest)."""
    cfg = _cfg_from_ctx(ctx)
    return _items(sorted(load_mappings(cfg).keys()), incomplete)


def iter_cli_params(cmd=None, path=()):
    """Yield (path_tuple, command, param) for every Argument/Option under `cmd` (default: root cli)."""
    if cmd is None:
        from .cli import cli as cmd
    if isinstance(cmd, click.Group):
        for name, sub in sorted(cmd.commands.items()):
            yield from iter_cli_params(sub, path + (name,))
    for param in cmd.params:
        yield path, cmd, param


def missing_required_shell_completes(cmd=None):
    """Return list of 'cmd.path:param' strings that violate REQUIRED_SHELL_COMPLETE_NAMES."""
    missing = []
    for path, _cmd, param in iter_cli_params(cmd):
        if param.name not in REQUIRED_SHELL_COMPLETE_NAMES:
            continue
        if isinstance(param, click.Option) and param.is_flag:
            continue
        if isinstance(param.type, (click.Path, click.Choice)):
            continue
        if getattr(param, "shell_complete", None) is not None:
            continue
        loc = " ".join(path) if path else "(root)"
        missing.append(f"{loc}:{param.name}")
    return missing
