#!/usr/bin/env python3
"""Lint docs/specs against the schema and the SPEC-0000 / SPEC-0003 rules, and generate the
LEDGER spec index.

Standalone: `python3 tools/spec_lint.py` (validate, exit non-zero on any violation) or
`python3 tools/spec_lint.py --write-ledger` (regenerate the LEDGER's generated block).
Also exposed as `wt spec lint` / `wt spec write-ledger` once the package is installed.

Checks:
  1. frontmatter validates against spec.schema.json (dates normalized to ISO strings)
  2. id matches the filename number
  3. required body sections present
  4. Test plan non-empty; feature/epic need a real plan (not "N/A"); policy/spike may N/A
  5. done specs have no unchecked boxes under Acceptance criteria / Definition of done
  6. supersedes / depends_on / superseded_by / parent reference existing specs
  7. parent resolves to a spec whose kind is 'epic'
  8. an epic marked done has every child done or superseded
  9. LEDGER's generated block is up to date (regenerate with --write-ledger)
"""
import argparse
import datetime as dt
import json
import re
import sys
from pathlib import Path

import yaml
import jsonschema

ROOT = Path(__file__).resolve().parent.parent
SPECS = ROOT / "docs" / "specs"
SCHEMA = SPECS / "spec.schema.json"
LEDGER = ROOT / "docs" / "LEDGER.md"

REQUIRED_SECTIONS = [
    "Context", "Decision", "Acceptance criteria", "Test plan", "Definition of done",
]
FILE_RE = re.compile(r"^(\d{4})-.+\.md$")
NA_RE = re.compile(r"(?i)^n/?a\b")

BEGIN = "<!-- specs:begin (generated by tools/spec_lint.py --write-ledger — do not edit by hand) -->"
END = "<!-- specs:end -->"
REGION_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

ACTIVE = ("draft", "proposed", "accepted", "in-progress")
CLOSED = ("superseded", "rejected")


def _normalize(o):
    """YAML parses unquoted dates to date objects; JSON Schema wants ISO strings."""
    if isinstance(o, dict):
        return {k: _normalize(v) for k, v in o.items()}
    if isinstance(o, list):
        return [_normalize(v) for v in o]
    if isinstance(o, (dt.date, dt.datetime)):
        return o.isoformat()
    return o


def split_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        return None, text
    return yaml.safe_load(m.group(1)), m.group(2)


def sections(body):
    """Map '## Heading' -> section text (until the next '## ')."""
    out, cur, buf = {}, None, []
    for line in body.splitlines():
        h = re.match(r"^##\s+(.*?)\s*$", line)
        if h:
            if cur is not None:
                out[cur] = "\n".join(buf).strip()
            cur, buf = h.group(1), []
        elif cur is not None:
            buf.append(line)
    if cur is not None:
        out[cur] = "\n".join(buf).strip()
    return out


def unchecked_boxes(section_text):
    return re.findall(r"^\s*-\s*\[ \]", section_text, re.M)


def load_specs():
    specs = []
    for path in sorted(SPECS.glob("[0-9]*.md")):
        text = path.read_text()
        fm, body = split_frontmatter(text)
        specs.append({
            "path": path,
            "file": path.name,
            "num": FILE_RE.match(path.name).group(1) if FILE_RE.match(path.name) else None,
            "fm": fm or {},
            "raw_fm_ok": fm is not None,
            "sections": sections(body),
            "id": (fm or {}).get("id", ""),
            "kind": (fm or {}).get("kind", "feature"),
            "status": (fm or {}).get("status", ""),
        })
    return specs


def validate(specs):
    schema = json.loads(SCHEMA.read_text())
    ids = {s["id"] for s in specs if s["id"]}
    by_id = {s["id"]: s for s in specs if s["id"]}
    children = {}
    for s in specs:
        p = s["fm"].get("parent")
        if p:
            children.setdefault(p, []).append(s)
    problems = []

    def err(s, msg):
        problems.append(f"{s['file']}: {msg}")

    for s in specs:
        if not s["raw_fm_ok"]:
            err(s, "no YAML frontmatter block")
            continue
        fm, secs = s["fm"], s["sections"]
        try:  # 1
            jsonschema.validate(_normalize(fm), schema)
        except jsonschema.ValidationError as e:
            err(s, f"schema: {e.message}")
        if s["num"] and s["id"] != f"SPEC-{s['num']}":  # 2
            err(s, f"id {s['id']!r} does not match filename number {s['num']}")
        for sec in REQUIRED_SECTIONS:  # 3
            if sec not in secs:
                err(s, f"missing required section '## {sec}'")
        tp = secs.get("Test plan", "")  # 4
        if not tp:
            err(s, "Test plan section is empty")
        elif s["kind"] in ("feature", "epic") and NA_RE.match(tp):
            err(s, f"kind '{s['kind']}' needs a real Test plan (N/A only for policy/spike)")
        if s["status"] == "done":  # 5
            for sec in ("Acceptance criteria", "Definition of done"):
                if unchecked_boxes(secs.get(sec, "")):
                    err(s, f"status 'done' but '## {sec}' has unchecked boxes")
        refs = list(fm.get("supersedes", []) or []) + list(fm.get("depends_on", []) or [])
        if fm.get("superseded_by"):
            refs.append(fm["superseded_by"])
        if fm.get("parent"):
            refs.append(fm["parent"])
        for r in refs:  # 6
            if r not in ids:
                err(s, f"references unknown spec {r}")
        parent = fm.get("parent")  # 7
        if parent and parent in by_id and by_id[parent]["kind"] != "epic":
            err(s, f"parent {parent} is not kind 'epic'")
        if s["kind"] == "epic" and s["status"] == "done":  # 8
            open_kids = [c["id"] for c in children.get(s["id"], [])
                         if c["status"] not in ("done", "superseded")]
            if open_kids:
                err(s, f"epic 'done' but children not finished: {', '.join(open_kids)}")

    # 9 ledger freshness
    if not LEDGER.exists():
        problems.append("LEDGER.md: missing")
    else:
        text = LEDGER.read_text()
        m = REGION_RE.search(text)
        want = _region(render_block(specs, children))
        if not m:
            problems.append("LEDGER.md: missing specs markers (add them, then --write-ledger)")
        elif m.group(0) != want:
            problems.append("LEDGER.md: generated block is stale — run `--write-ledger`")
    return problems


STALE_IDEA_STATES = {"IDEA", "INCUBATE", "SPECCED"}


def check_source_idea_promotion(specs):
    """Advisory check (NOT part of `validate`/the pytest-gated lint): flag a 'done' spec whose
    `source_idea` never left the pre-promotion states. PROMOTED only happens as a side-effect
    of `wt spec generate` (specs.py:generate_from_spec) — a spec whose code was written by hand
    without running generate leaves its idea stuck at IDEA/INCUBATE/SPECCED forever with
    nothing flagging it.

    Deliberately excluded from `validate()`: it reads the live `org_ideas_file` via the `wt`
    package (config + org parsing) — a machine-local file outside this repo, not deterministic
    repo content — so it must never gate `uv run pytest` or run in an environment without `wt`
    importable (e.g. a bare `python3` without the project's venv). Run explicitly via
    `python3 tools/spec_lint.py --check-source-ideas` (inside `uv run`, or any env with `wt`
    on the path)."""
    from wt.config import load_config
    from wt.org import load_tasks

    cfg = load_config()
    ideas_by_id = {t.properties.get("ID"): t for t in load_tasks(cfg)
                  if t.is_idea and t.properties.get("ID")}
    problems = []
    for s in specs:
        source_idea = s["fm"].get("source_idea")
        if not source_idea or s["status"] != "done":
            continue
        idea = ideas_by_id.get(source_idea)
        if idea is None:
            problems.append(f"{s['file']}: source_idea {source_idea} not found in the ideas file")
            continue
        state = (idea.state or "").upper()
        if state in STALE_IDEA_STATES:
            problems.append(
                f"{s['file']}: status: done but source_idea {source_idea} is still {state} — "
                f"run `wt spec generate {s['id']}` or advance it "
                f"(`wt state {source_idea} PROMOTED`)")
    return problems


def _link(s):
    return f"[{s['id']}](./specs/{s['file']})"


def _row(s):
    fm = s["fm"]
    return (f"| {_link(s)} | {fm.get('title', '')} | {s['kind']} | {s['status']} | "
            f"{fm.get('milestone', '—')} | {fm.get('updated', fm.get('created', ''))} |")


def _table(rows):
    head = ("| ID | Title | Kind | Status | Milestone | Updated |\n"
            "|----|-------|------|--------|-----------|---------|")
    return "\n".join([head] + rows) if rows else "_None._"


def render_block(specs, children=None):
    if children is None:
        children = {}
        for s in specs:
            if s["fm"].get("parent"):
                children.setdefault(s["fm"]["parent"], []).append(s)
    by_num = sorted(specs, key=lambda s: s["num"] or "")
    epics = [s for s in by_num if s["kind"] == "epic"]

    lines = ["## Epics", ""]
    if not epics:
        lines += ["_No epics yet._", ""]
    else:
        for e in epics:
            kids = sorted(children.get(e["id"], []), key=lambda s: s["num"] or "")
            done = sum(1 for c in kids if c["status"] in ("done", "superseded"))
            lines.append(f"- **{_link(e)} — {e['fm'].get('title','')}** · "
                         f"{e['status']} · ({done}/{len(kids)} done)")
            for c in kids:
                box = "x" if c["status"] in ("done", "superseded") else " "
                lines.append(f"  - [{box}] {_link(c)} {c['fm'].get('title','')} — {c['status']}")
            if not kids:
                lines.append("  - _(no child specs yet)_")
        lines.append("")

    lines += ["## Active & planned", ""]
    lines.append(_table([_row(s) for s in by_num if s["status"] in ACTIVE]))
    lines += ["", "## Done", ""]
    lines.append(_table([_row(s) for s in by_num if s["status"] == "done"]))
    lines += ["", "## Superseded / rejected", ""]
    lines.append(_table([_row(s) for s in by_num if s["status"] in CLOSED]))
    return "\n".join(lines)


def _region(block):
    return f"{BEGIN}\n\n{block}\n\n{END}"


def write_ledger(specs):
    text = LEDGER.read_text()
    region = _region(render_block(specs))
    if not REGION_RE.search(text):
        print(f"✗ LEDGER.md has no specs markers; add:\n{BEGIN}\n{END}", file=sys.stderr)
        return 1
    LEDGER.write_text(REGION_RE.sub(lambda m: region, text))
    print(f"✓ wrote generated ledger block ({len(specs)} specs) → {LEDGER}")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Lint specs / regenerate the ledger block.")
    ap.add_argument("--write-ledger", action="store_true",
                    help="regenerate LEDGER.md's generated block from spec frontmatter")
    ap.add_argument("--check-source-ideas", action="store_true",
                    help="advisory: flag 'done' specs whose source_idea is still stuck at "
                         "IDEA/INCUBATE/SPECCED (reads the live ideas file; requires `wt` "
                         "importable — run via `uv run`; not part of the main lint/pytest gate)")
    args = ap.parse_args()
    specs = load_specs()
    if args.write_ledger:
        return write_ledger(specs)
    if args.check_source_ideas:
        try:
            problems = check_source_idea_promotion(specs)
        except Exception as e:
            print(f"✗ could not run source_idea check: {e}", file=sys.stderr)
            return 1
        if problems:
            print(f"✗ {len(problems)} stale source_idea(s):", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            return 1
        print("✓ no stale source_idea states")
        return 0
    problems = validate(specs)
    if problems:
        print(f"✗ {len(problems)} problem(s) in {len(specs)} spec(s):", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    print(f"✓ {len(specs)} spec(s) OK: {', '.join(sorted(s['id'] for s in specs))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
